### ISSUE TITLE
Multi language; Keine hart codierten Strings

### ISSUE THREAD

**Issue by rubengees** [rubengees/findme-react-native#9]
Derzeit werden noch an allen Stellen hartcodierte Strings benutzt. Außerdem gibt es derzeit keine Möglichkeit diese in verschiedenen Sprachen darzustellen.
Folgende Bibliothek habe ich gefunden die das unterstützt: https://www.npmjs.com/package/react-native-localization
Meinungen?

**Comment by ewolf1** [comment]
Wenn es die Entwicklung nicht wesentlich komplizierter macht würde es auf jeden Fall Sinn machen.
Sonst jedoch würde ich sagen wir stellen die App an sich erst fertig und machen das dann in einem Update wenn Zeit ist.

**Comment by rubengees** [comment]
Für sowas werden wir wohl keine Zeit zu haben, ich schließe also.
